// Code generated by protoc-gen-go. DO NOT EDIT.
// source: opencensus/proto/agent/common/v1/common.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LibraryInfo_Language int32

const (
	LibraryInfo_LANGUAGE_UNSPECIFIED LibraryInfo_Language = 0
	LibraryInfo_CPP                  LibraryInfo_Language = 1
	LibraryInfo_C_SHARP              LibraryInfo_Language = 2
	LibraryInfo_ERLANG               LibraryInfo_Language = 3
	LibraryInfo_GO_LANG              LibraryInfo_Language = 4
	LibraryInfo_JAVA                 LibraryInfo_Language = 5
	LibraryInfo_NODE_JS              LibraryInfo_Language = 6
	LibraryInfo_PHP                  LibraryInfo_Language = 7
	LibraryInfo_PYTHON               LibraryInfo_Language = 8
	LibraryInfo_RUBY                 LibraryInfo_Language = 9
)

var LibraryInfo_Language_name = map[int32]string{
	0: "LANGUAGE_UNSPECIFIED",
	1: "CPP",
	2: "C_SHARP",
	3: "ERLANG",
	4: "GO_LANG",
	5: "JAVA",
	6: "NODE_JS",
	7: "PHP",
	8: "PYTHON",
	9: "RUBY",
}

var LibraryInfo_Language_value = map[string]int32{
	"LANGUAGE_UNSPECIFIED": 0,
	"CPP":                  1,
	"C_SHARP":              2,
	"ERLANG":               3,
	"GO_LANG":              4,
	"JAVA":                 5,
	"NODE_JS":              6,
	"PHP":                  7,
	"PYTHON":               8,
	"RUBY":                 9,
}

func (x LibraryInfo_Language) String() string {
	return proto.EnumName(LibraryInfo_Language_name, int32(x))
}

func (LibraryInfo_Language) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_126c72ed8a252c84, []int{2, 0}
}

// Identifier metadata of the Node that produces the span or tracing data.
// Note, this is not the metadata about the Node or service that is described by associated spans.
// In the future we plan to extend the identifier proto definition to support
// additional information (e.g cloud id, etc.)
type Node struct {
	// Identifier that uniquely identifies a process within a VM/container.
	Identifier *ProcessIdentifier `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// Information on the OpenCensus Library that initiates the stream.
	LibraryInfo *LibraryInfo `protobuf:"bytes,2,opt,name=library_info,json=libraryInfo,proto3" json:"library_info,omitempty"`
	// Additional information on service.
	ServiceInfo *ServiceInfo `protobuf:"bytes,3,opt,name=service_info,json=serviceInfo,proto3" json:"service_info,omitempty"`
	// Additional attributes.
	Attributes           map[string]string `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Node) Reset()         { *m = Node{} }
func (m *Node) String() string { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()    {}
func (*Node) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c72ed8a252c84, []int{0}
}

func (m *Node) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Node.Unmarshal(m, b)
}
func (m *Node) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Node.Marshal(b, m, deterministic)
}
func (m *Node) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Node.Merge(m, src)
}
func (m *Node) XXX_Size() int {
	return xxx_messageInfo_Node.Size(m)
}
func (m *Node) XXX_DiscardUnknown() {
	xxx_messageInfo_Node.DiscardUnknown(m)
}

var xxx_messageInfo_Node proto.InternalMessageInfo

func (m *Node) GetIdentifier() *ProcessIdentifier {
	if m != nil {
		return m.Identifier
	}
	return nil
}

func (m *Node) GetLibraryInfo() *LibraryInfo {
	if m != nil {
		return m.LibraryInfo
	}
	return nil
}

func (m *Node) GetServiceInfo() *ServiceInfo {
	if m != nil {
		return m.ServiceInfo
	}
	return nil
}

func (m *Node) GetAttributes() map[string]string {
	if m != nil {
		return m.Attributes
	}
	return nil
}

// Identifier that uniquely identifies a process within a VM/container.
type ProcessIdentifier struct {
	// The host name. Usually refers to the machine/container name.
	// For example: os.Hostname() in Go, socket.gethostname() in Python.
	HostName string `protobuf:"bytes,1,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	// Process id.
	Pid uint32 `protobuf:"varint,2,opt,name=pid,proto3" json:"pid,omitempty"`
	// Start time of this ProcessIdentifier. Represented in epoch time.
	StartTimestamp       *timestamp.Timestamp `protobuf:"bytes,3,opt,name=start_timestamp,json=startTimestamp,proto3" json:"start_timestamp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ProcessIdentifier) Reset()         { *m = ProcessIdentifier{} }
func (m *ProcessIdentifier) String() string { return proto.CompactTextString(m) }
func (*ProcessIdentifier) ProtoMessage()    {}
func (*ProcessIdentifier) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c72ed8a252c84, []int{1}
}

func (m *ProcessIdentifier) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProcessIdentifier.Unmarshal(m, b)
}
func (m *ProcessIdentifier) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProcessIdentifier.Marshal(b, m, deterministic)
}
func (m *ProcessIdentifier) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProcessIdentifier.Merge(m, src)
}
func (m *ProcessIdentifier) XXX_Size() int {
	return xxx_messageInfo_ProcessIdentifier.Size(m)
}
func (m *ProcessIdentifier) XXX_DiscardUnknown() {
	xxx_messageInfo_ProcessIdentifier.DiscardUnknown(m)
}

var xxx_messageInfo_ProcessIdentifier proto.InternalMessageInfo

func (m *ProcessIdentifier) GetHostName() string {
	if m != nil {
		return m.HostName
	}
	return ""
}

func (m *ProcessIdentifier) GetPid() uint32 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProcessIdentifier) GetStartTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.StartTimestamp
	}
	return nil
}

// Information on OpenCensus Library.
type LibraryInfo struct {
	// Language of OpenCensus Library.
	Language LibraryInfo_Language `protobuf:"varint,1,opt,name=language,proto3,enum=opencensus.proto.agent.common.v1.LibraryInfo_Language" json:"language,omitempty"`
	// Version of Agent exporter of Library.
	ExporterVersion string `protobuf:"bytes,2,opt,name=exporter_version,json=exporterVersion,proto3" json:"exporter_version,omitempty"`
	// Version of OpenCensus Library.
	CoreLibraryVersion   string   `protobuf:"bytes,3,opt,name=core_library_version,json=coreLibraryVersion,proto3" json:"core_library_version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LibraryInfo) Reset()         { *m = LibraryInfo{} }
func (m *LibraryInfo) String() string { return proto.CompactTextString(m) }
func (*LibraryInfo) ProtoMessage()    {}
func (*LibraryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c72ed8a252c84, []int{2}
}

func (m *LibraryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LibraryInfo.Unmarshal(m, b)
}
func (m *LibraryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LibraryInfo.Marshal(b, m, deterministic)
}
func (m *LibraryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LibraryInfo.Merge(m, src)
}
func (m *LibraryInfo) XXX_Size() int {
	return xxx_messageInfo_LibraryInfo.Size(m)
}
func (m *LibraryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_LibraryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_LibraryInfo proto.InternalMessageInfo

func (m *LibraryInfo) GetLanguage() LibraryInfo_Language {
	if m != nil {
		return m.Language
	}
	return LibraryInfo_LANGUAGE_UNSPECIFIED
}

func (m *LibraryInfo) GetExporterVersion() string {
	if m != nil {
		return m.ExporterVersion
	}
	return ""
}

func (m *LibraryInfo) GetCoreLibraryVersion() string {
	if m != nil {
		return m.CoreLibraryVersion
	}
	return ""
}

// Additional service information.
type ServiceInfo struct {
	// Name of the service.
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServiceInfo) Reset()         { *m = ServiceInfo{} }
func (m *ServiceInfo) String() string { return proto.CompactTextString(m) }
func (*ServiceInfo) ProtoMessage()    {}
func (*ServiceInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_126c72ed8a252c84, []int{3}
}

func (m *ServiceInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServiceInfo.Unmarshal(m, b)
}
func (m *ServiceInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServiceInfo.Marshal(b, m, deterministic)
}
func (m *ServiceInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServiceInfo.Merge(m, src)
}
func (m *ServiceInfo) XXX_Size() int {
	return xxx_messageInfo_ServiceInfo.Size(m)
}
func (m *ServiceInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ServiceInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ServiceInfo proto.InternalMessageInfo

func (m *ServiceInfo) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterEnum("opencensus.proto.agent.common.v1.LibraryInfo_Language", LibraryInfo_Language_name, LibraryInfo_Language_value)
	proto.RegisterType((*Node)(nil), "opencensus.proto.agent.common.v1.Node")
	proto.RegisterMapType((map[string]string)(nil), "opencensus.proto.agent.common.v1.Node.AttributesEntry")
	proto.RegisterType((*ProcessIdentifier)(nil), "opencensus.proto.agent.common.v1.ProcessIdentifier")
	proto.RegisterType((*LibraryInfo)(nil), "opencensus.proto.agent.common.v1.LibraryInfo")
	proto.RegisterType((*ServiceInfo)(nil), "opencensus.proto.agent.common.v1.ServiceInfo")
}

func init() {
	proto.RegisterFile("opencensus/proto/agent/common/v1/common.proto", fileDescriptor_126c72ed8a252c84)
}

var fileDescriptor_126c72ed8a252c84 = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x4f, 0x6e, 0xd3, 0x40,
	0x14, 0xc6, 0x71, 0x9c, 0xb6, 0xc9, 0x33, 0xb4, 0x66, 0xd4, 0x45, 0x54, 0x16, 0x84, 0xb0, 0x29,
	0x8b, 0xd8, 0xb4, 0x95, 0x10, 0x42, 0x62, 0xe1, 0xa6, 0xa1, 0x4d, 0x55, 0x25, 0x96, 0xd3, 0x46,
	0x2a, 0x1b, 0xcb, 0x49, 0x27, 0xee, 0x88, 0x78, 0x26, 0x9a, 0x19, 0x47, 0xf4, 0x04, 0x88, 0x0b,
	0x70, 0x00, 0x8e, 0xc3, 0x51, 0x38, 0x05, 0x9a, 0x19, 0x27, 0xb1, 0xe8, 0x22, 0xdd, 0xbd, 0x7f,
	0xdf, 0xef, 0x59, 0xdf, 0x3c, 0x19, 0xda, 0x6c, 0x8e, 0xe9, 0x04, 0x53, 0x91, 0x0b, 0x7f, 0xce,
	0x99, 0x64, 0x7e, 0x92, 0x62, 0x2a, 0xfd, 0x09, 0xcb, 0x32, 0x46, 0xfd, 0xc5, 0x51, 0x11, 0x79,
	0xba, 0x89, 0x9a, 0xeb, 0x71, 0x53, 0xf1, 0xf4, 0xb8, 0x57, 0x0c, 0x2d, 0x8e, 0x0e, 0x5e, 0xa7,
	0x8c, 0xa5, 0x33, 0x6c, 0x60, 0xe3, 0x7c, 0xea, 0x4b, 0x92, 0x61, 0x21, 0x93, 0x6c, 0x6e, 0x04,
	0xad, 0x5f, 0x36, 0x54, 0xfb, 0xec, 0x0e, 0xa3, 0x21, 0x00, 0xb9, 0xc3, 0x54, 0x92, 0x29, 0xc1,
	0xbc, 0x61, 0x35, 0xad, 0x43, 0xe7, 0xf8, 0xc4, 0xdb, 0xb4, 0xc0, 0x0b, 0x39, 0x9b, 0x60, 0x21,
	0x7a, 0x2b, 0x69, 0x54, 0xc2, 0xa0, 0x10, 0x9e, 0xcf, 0xc8, 0x98, 0x27, 0xfc, 0x21, 0x26, 0x74,
	0xca, 0x1a, 0x15, 0x8d, 0x6d, 0x6f, 0xc6, 0x5e, 0x19, 0x55, 0x8f, 0x4e, 0x59, 0xe4, 0xcc, 0xd6,
	0x89, 0x22, 0x0a, 0xcc, 0x17, 0x64, 0x82, 0x0d, 0xd1, 0x7e, 0x2a, 0x71, 0x68, 0x54, 0x86, 0x28,
	0xd6, 0x09, 0x1a, 0x01, 0x24, 0x52, 0x72, 0x32, 0xce, 0x25, 0x16, 0x8d, 0x6a, 0xd3, 0x3e, 0x74,
	0x8e, 0x3f, 0x6c, 0xe6, 0x29, 0xd3, 0xbc, 0x60, 0x25, 0xec, 0x52, 0xc9, 0x1f, 0xa2, 0x12, 0xe9,
	0xe0, 0x33, 0xec, 0xfd, 0xd7, 0x46, 0x2e, 0xd8, 0xdf, 0xf0, 0x83, 0x36, 0xb7, 0x1e, 0xa9, 0x10,
	0xed, 0xc3, 0xd6, 0x22, 0x99, 0xe5, 0x58, 0x3b, 0x53, 0x8f, 0x4c, 0xf2, 0xa9, 0xf2, 0xd1, 0x6a,
	0xfd, 0xb0, 0xe0, 0xe5, 0x23, 0x73, 0xd1, 0x2b, 0xa8, 0xdf, 0x33, 0x21, 0x63, 0x9a, 0x64, 0xb8,
	0xe0, 0xd4, 0x54, 0xa1, 0x9f, 0x64, 0x58, 0xe1, 0xe7, 0xe4, 0x4e, 0xa3, 0x5e, 0x44, 0x2a, 0x44,
	0x1d, 0xd8, 0x13, 0x32, 0xe1, 0x32, 0x5e, 0x3d, 0x7b, 0x61, 0xd8, 0x81, 0x67, 0x0e, 0xc3, 0x5b,
	0x1e, 0x86, 0x77, 0xbd, 0x9c, 0x88, 0x76, 0xb5, 0x64, 0x95, 0xb7, 0xfe, 0x54, 0xc0, 0x29, 0xbd,
	0x07, 0x8a, 0xa0, 0x36, 0x4b, 0x68, 0x9a, 0x27, 0xa9, 0xf9, 0x84, 0xdd, 0xa7, 0xd8, 0x55, 0x02,
	0x78, 0x57, 0x85, 0x3a, 0x5a, 0x71, 0xd0, 0x3b, 0x70, 0xf1, 0xf7, 0x39, 0xe3, 0x12, 0xf3, 0x78,
	0x81, 0xb9, 0x20, 0x8c, 0x16, 0x96, 0xec, 0x2d, 0xeb, 0x23, 0x53, 0x46, 0xef, 0x61, 0x7f, 0xc2,
	0x38, 0x8e, 0x97, 0x87, 0xb5, 0x1c, 0xb7, 0xf5, 0x38, 0x52, 0xbd, 0x62, 0x59, 0xa1, 0x68, 0xfd,
	0xb4, 0xa0, 0xb6, 0xdc, 0x89, 0x1a, 0xb0, 0x7f, 0x15, 0xf4, 0xcf, 0x6f, 0x82, 0xf3, 0x6e, 0x7c,
	0xd3, 0x1f, 0x86, 0xdd, 0x4e, 0xef, 0x4b, 0xaf, 0x7b, 0xe6, 0x3e, 0x43, 0x3b, 0x60, 0x77, 0xc2,
	0xd0, 0xb5, 0x90, 0x03, 0x3b, 0x9d, 0x78, 0x78, 0x11, 0x44, 0xa1, 0x5b, 0x41, 0x00, 0xdb, 0xdd,
	0x48, 0x29, 0x5c, 0x5b, 0x35, 0xce, 0x07, 0xb1, 0x4e, 0xaa, 0xa8, 0x06, 0xd5, 0xcb, 0x60, 0x14,
	0xb8, 0x5b, 0xaa, 0xdc, 0x1f, 0x9c, 0x75, 0xe3, 0xcb, 0xa1, 0xbb, 0xad, 0x28, 0xe1, 0x45, 0xe8,
	0xee, 0x28, 0x61, 0x78, 0x7b, 0x7d, 0x31, 0xe8, 0xbb, 0x35, 0x35, 0x1b, 0xdd, 0x9c, 0xde, 0xba,
	0xf5, 0xd6, 0x1b, 0x70, 0x4a, 0x97, 0x88, 0x10, 0x54, 0x4b, 0x4f, 0xa9, 0xe3, 0xd3, 0xdf, 0x16,
	0xbc, 0x25, 0x6c, 0xa3, 0xa5, 0xa7, 0x4e, 0x47, 0x87, 0xa1, 0x6a, 0x86, 0xd6, 0xd7, 0x5e, 0x4a,
	0xe4, 0x7d, 0x3e, 0x56, 0x03, 0xbe, 0xd1, 0xb5, 0x09, 0x15, 0x92, 0xe7, 0x19, 0xa6, 0x32, 0x91,
	0x84, 0x51, 0x7f, 0x8d, 0x6c, 0x9b, 0xbf, 0x4b, 0x8a, 0x69, 0x3b, 0x7d, 0xf4, 0x93, 0xf9, 0x5b,
	0x69, 0x0e, 0xe6, 0x98, 0x76, 0xcc, 0x72, 0xcd, 0xf7, 0x02, 0xbd, 0xdc, 0x6c, 0xf4, 0x46, 0x47,
	0xe3, 0x6d, 0x0d, 0x38, 0xf9, 0x17, 0x00, 0x00, 0xff, 0xff, 0xd2, 0x81, 0xfa, 0xac, 0xb2, 0x04,
	0x00, 0x00,
}
